name: Android CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Get commit details
        id: commit_info
        run: |
          echo ::set-output name=commit_count::$(git rev-list --count ${{ github.event.before }}..${{ github.event.after }} || echo 0)
          COMMIT_LOG=$(git log --pretty=format:"%h %s" --abbrev-commit ${{ github.event.before }}..${{ github.event.after }} || echo null)
          COMMIT_LOG="${COMMIT_LOG//'%'/'%25'}"
          COMMIT_LOG="${COMMIT_LOG//$'\n'/'%0A'}"
          COMMIT_LOG="${COMMIT_LOG//$'\r'/'%0D'}"
          echo ::set-output name=commit_log::$COMMIT_LOG

      - name: Send a message about the latest commit
        run: |
          curl \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d disable_notification=true \
          -d parse_mode=HTML \
          --data-urlencode "text=\
          ↗️ <b>PUSH</b>
          <b>was made at:</b> ${{ github.repository }}
          <b>by:</b> <u>${{ github.actor }}</u>
          <b>commits pushed:</b> ${{ steps.commit_info.outputs.commit_count }}
          <b>commit log:</b>
          <pre>${{ steps.commit_info.outputs.commit_log }}</pre>
          
          <b>url:</b> https://github.com/${{ github.repository }}/commit/${{ github.sha }}" \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle
          cp .github/runner-files/ci-gradle.properties ~/.gradle/gradle.properties
      
      - name: Extract debug.keystore
        run: |
          mkdir -p ~/.android
          echo "${{ secrets.DEBUG_KEYSTORE }}" | base64 -d > ~/.android/debug.keystore

      - name: Build app
        uses: gradle/gradle-command-action@v1
        with:
          arguments: assembleDebug
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true

      # - name: Delete previous continuous release
      #   if: "contains(github.event.head_commit.message, '#genapk')"
      #   run: |
      #     if git show-ref --tags | egrep -q "refs/tags/continuous"
      #     then
      #         release_query=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -s \
      #         https://api.github.com/repos/${{ github.repository }}/releases \
      #         | jq '. | map(select(.tag_name == "continuous"))[0]')
      #         curl -i -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X DELETE \
      #         https://api.github.com/repos/${{ github.repository }}/releases/assets/$(echo $release_query | jq .assets[0].id)
      #         curl -i -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X DELETE \
      #         https://api.github.com/repos/${{ github.repository }}/releases/$(echo $release_query | jq .id)
      #         git tag -d continuous
      #         curl -i -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X DELETE \
      #         https://api.github.com/repos/${{ github.repository }}/git/refs/tags/continuous
      #         sleep 1 #required else next action will fail
      #     else 
      #         echo "tag not found"
      #     fi
      # - name: Create Release
      #   if: "contains(github.event.head_commit.message, '#genapk')"
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: continuous
      #     release_name: continuous-build-r${{ steps.commit_info.outputs.commit_count }}
      #     draft: false
      #     prerelease: true

      # - name: Upload Release Asset
      #   if: "contains(github.event.head_commit.message, '#genapk')"
      #   id: upload-release-asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./app/build/outputs/apk/debug/app-debug.apk
      #     asset_name: app-debug.apk
      #     asset_content_type: application/zip

      # - name: Send a message about the release
      #   if: "contains(github.event.head_commit.message, '#genapk')"
      #   run: |
      #     curl \
      #     -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
      #     -d disable_notification=true \
      #     -d parse_mode=HTML \
      #     -d text=\
      #     "📱 <b>Debug Apk released</b>%0A\
      #     url: https://github.com/${{ github.repository }}/releases/tag/continuous" \
      #     "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"

      - name: Send apk to chat
        if: contains(github.event.head_commit.message, 'tgapk') || github.event_name == 'workflow_dispatch'
        run: |
          curl \
          -F chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -F disable_notification=true \
          -F parse_mode=HTML \
          -F caption=\
          "📱 <b>Debug Apk released</b>" \
          -F document=@"./app/build/outputs/apk/debug/app-debug.apk" \
          https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument

      - name: Send a message if build fails
        if: failure()
        run: |
          curl \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d disable_notification=true \
          -d parse_mode=HTML \
          -d text=\
          "❌ <b><u>BUILD FAILED!!!</u></b>%0A\
          <b>job url:</b> https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"